name: SodionAuth
version: ${version}
main: red.mohist.sodionauth.bungee.BungeeLoader
authors:
  - logos
  - ishland
description: A new generation of authentication plugin for Minecraft
website: https://mohist.red/