# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: SodionAuth-All-dev
          path: build/libs/*.jar
      - uses: actions/upload-artifact@v2
        with:
          name: SodionAuth-Bukkit-dev
          path: SodionAuth-Bukkit/build/libs/*-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: SodionAuth-Fabric-dev
          path: SodionAuth-Fabric/build/libs/*-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: SodionAuth-Sponge-dev
          path: SodionAuth-Sponge/build/libs/*-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: SodionAuth-YggdrasilServer-dev
          path: SodionAuth-YggdrasilServer/build/libs/*-all.jar
